### ISSUE TITLE
Not providing desired functionality on first component mount

### ISSUE THREAD

**Issue by kyleconnolly1020** [davidcetinkaya/embla-carousel-react#12]
Hi David, 

Upon mounting the embla carousel for the first time, the carousel displays the following undesired behaviors: 

- Dragging or clicking prev/next will always move the slides the entire width of the container. I am displaying multiple slides within the viewport at once, so this ends up skipping many slides. As a result, there ends up being a large empty space after the last child has been passed, due to embla thinking that there are many more slide nodes to iterate through. 

- Additionally, slides prior to the first index are not displayed at all (I have the 'loop' value set to true). I believe that this is also related to the large empty space that is render after the last "real" slide. 

Once I leave the page and come back (the same component remounts), embla works exactly as desired. I have tried creating the carousel as both a class component and as a functional component with Hooks, however both times this unwanted behavior has appeared. 

For reference, I have attached gifs of the behavior. 
1st - shows the slides moving the entire width of the container on the first mount
2nd - shows the large empty space after the last child (before the first child) on the first mount
3rd - shows the desired behavior once coming back to the page (component remounted)

Hopefully that can explain it better than I can :)
Thanks!

![firstMount_SlideSkipping](https://user-images.githubusercontent.com/8386975/74208762-c4fd4180-4c39-11ea-9382-99b2fdeb2e91.gif)
![firstMount_emptySpace](https://user-images.githubusercontent.com/8386975/74208771-caf32280-4c39-11ea-9dab-b625623ee8cb.gif)
![secondMount_DesiredBehavior](https://user-images.githubusercontent.com/8386975/74208772-caf32280-4c39-11ea-9631-4b4684dea669.gif)

**Comment by davidcetinkaya** [comment]
Hi Kyle(@kyleconnolly1020),

Thanks for reporting this and the provided gifs. But in order to investigate further, I need some code to work with, so I would appreciate if you could fork [this CodeSandbox](https://codesandbox.io/embed/embla-carousel-react-znjzv?codemirror=1) to demonstrate the issue. At this point I can’t determine if the issue is caused by the package itself or if it’s related to an improper setup.

Kindly,
David

**Comment by kyleconnolly1020** [comment]
No problem. Please check out [this CodeSandbox](https://codesandbox.io/embed/embla-carousel-react-znjzv?codemirror=1). The project in question is quite hefty, so I stripped out everything other than the code handling this functionality. Please refer to the 'GameView' and 'PlayerWheel' Components in specific for where I am using the embla package. 

Within the sandbox, please view the interpreter window in full-width. Click on the first object to view a carousel with 20 nodes, which displays the aforementioned behavior from my first message. Click on the second object to view a carousel with 6 nodes, which also acts funny given that there are less slides than the width of the slide container. 

Once in the carousel view, click the on the image (should be default placeholder image) to take you back to the first screen. Clicking refresh on the interpreter window will reproduce the undesired behavior on the **first carousel viewed after refresh**. 

Please let me know if you need any additional information. I really appreciate your input. 

Thank you, 
Kyle

**Comment by davidcetinkaya** [comment]
Hi Kyle (@kyleconnolly1020),

Thanks for the sandbox and reducing the test case, I'll see if I can debug what's going on 👍. I just glanced at the code and it seems like there's a race condition happening or similar. Because if I trigger a recalculation of Embla upon initialisation in the `PlayerWheel.js` file, it calculates everything as it should:

```jsx
const PlayerWheel = ({ children }) => {
    const [embla, setEmbla] = useState(null);
    const scrollPrev = useCallback(() => embla.scrollPrev(), [embla])
    const scrollNext = useCallback(() => embla.scrollNext(), [embla])  

    useEffect(() => {
        if (embla) {
            embla.on('select', () => {
                console.log(`Current index is ${embla.selectedScrollSnap() + 1}`);
            })
            embla.changeOptions({}); // This will recalculate everything
        }
    }, [embla]);

//...
```

In the meantime, I suggest you have a look at [this CodeSandbox](https://codesandbox.io/s/embla-carousel-react-github-issue-7-qrhnh). It makes use of react router and in this case Embla works as expected. Maybe it will help you to debug your code further.

Kindly,
David

**Comment by kyleconnolly1020** [comment]
Ok I will check out the sandbox to see if I can gather any insights. Hopefully we can uncover the root of the issue. Thank you for looking into this further!

**Comment by omarkhatibco** [comment]
Hi @kyleconnolly1020 

I had a similar problem, I think you fetch data from API ? 

I am not sure why but it's seems Embla start calculating once it had mounted

as a Workaround I do this 

```js
			{!loading && data.length > 0 && (
				<EmblaCarouselReact
					emblaRef={setEmbla}
					options={{ loop: false, align: 'start', dragFree: false, containScroll: true }}>
					<Flex
						cursor='grab'
						css={css({
							direction: 'ltr',
						})}
						direction='row-reverse'
						justifyContent='flex-end'>
						{data?.map(props => {
							return (
								<Box flex='0 0 100%' width='100%' minHeight='100%' key={props.id}>
									<HomeSlide key={data?.id} data={props} />
								</Box>
							);
						})}
					</Flex>
				</EmblaCarouselReact>
			)}

```

**Comment by lifedup** [comment]
> * I believe that this is also related to the large empty space that is render after the last "real" slide.

I had a large white space the width of the container after the last slide when set to loop.  It was caused by incorrect styles.  In my case I did not have position: relative on each of my slides.

**Comment by davidcetinkaya** [comment]
I'm going to close this due to lack of response. Feel free to re-open it if you would like further assistance.

Thanks a bunch for the help @lifedup and @omarkhatibco 💪!
