### ISSUE TITLE
Loop not working as expected

### ISSUE THREAD

**Issue by kennycrosby** [davidcetinkaya/embla-carousel-react#14]
Setting `loop: true` will slide to nothing after the last slide and then after some delay slide `0` shows up.

**Comment by kennycrosby** [comment]
Just realized I needed to add `position: relative;` to my slide. Solved the problem. Thanks for this awesome library!

**Comment by davidcetinkaya** [comment]
Thanks @kennycrosby,

As you have already figured out, `position: relative` is needed on the slides 🙂. For other users running into the same problem, please check out the [Quickstart section](https://github.com/davidcetinkaya/embla-carousel#quickstart).
