### ISSUE TITLE
Error on webpack rebuild

### ISSUE THREAD

**Issue by kennycrosby** [davidcetinkaya/embla-carousel-react#15]
I don't think this is necessarily breaking anything but I am getting:
`Uncaught TypeError: Cannot read property 'removeAllEvents' of undefined` 

Whenever webpack rebuilds. On refresh this doesn't happen. 

Seems to occur at the cleanup code: `return () => embla && embla.destroy();`

Since it's checking for embla first I'm not sure why it would result in undefined.

**Comment by davidcetinkaya** [comment]
Hello Kenny (@kennycrosby),

Thanks for reporting this. Could this be related to [issue #13](https://github.com/davidcetinkaya/embla-carousel-react/issues/13) maybe?

Please take a look and let me know if it solves your issue.

Best,
David

**Comment by kennycrosby** [comment]
@davidcetinkaya ahh ok so that line is actually not needed anymore. Looks like it is still in the codesandbox: https://codesandbox.io/s/embla-carousel-react-iox4t

That solves the issue though, thanks again!

**Comment by davidcetinkaya** [comment]
That's correct Kenny (@kennycrosby) 👍.

Ah I see, thanks for pointing that out. I removed that line on the [`Basic Setup`](https://codesandbox.io/s/embla-carousel-react-znjzv) example but the [`Autoplay`](https://codesandbox.io/s/embla-carousel-react-iox4t) example is Alans work (@readeral).

Alan (@readeral), would you mind bumping the `embla-carousel-react` version to the latest and removing the line in your CodeSandbox?

Thanks in advance.

Kindly,
David

**Comment by davidcetinkaya** [comment]
Duplicate of issue #13.

**Comment by readeral** [comment]
@davidcetinkaya Fixed. Thanks for the heads up!

**Comment by davidcetinkaya** [comment]
Thanks a lot Alan (@readeral) 🙂.

Cheers!
David

**Comment by readeral** [comment]
FWIW @davidcetinkaya I've created a 'team' on CodeSandBox for Embla-React and added this example to it, and invited you to the team, on the occasion you might want to edit that sandbox example.

**Comment by davidcetinkaya** [comment]
Hello Alan (@readeral),
I like the initiative! That's a great idea ⭐️. Just one thought. What about making it more generic and call it `embla-carousel`? So any team members invited will have access to edit any Embla CodeSandbox?

Best,
David
