### ISSUE TITLE
React Autoplay example

### ISSUE THREAD

**Issue by readeral** [davidcetinkaya/embla-carousel-react#2]
Hi David,

I've forked your React example to [include an autoplay example](https://codesandbox.io/s/embla-carousel-react-iox4t), based on [this post by Dan Abramov](https://overreacted.io/making-setinterval-declarative-with-react-hooks/)

I'm not sure if it's worth including in the Readme or not, but figured it would help someone else given setInterval can get a little hairy in React. I had to do a bit of googling to work this out!

Al

**Comment by davidcetinkaya** [comment]
Hi @readeral,

Sweet ⭐️! Thank you very much for sharing this 👍.

I'm thinking about creating a section in the **README** called **Inspiration** or similar to provide users with useful links, and I think your [autoplay example](https://codesandbox.io/s/embla-carousel-react-iox4t) would be great to put there.

What do you think?
Do you have any input on how we should do this?

**Comment by readeral** [comment]
Whatever is most easily maintained!

Adding an Inspiration section to Readme as you've said seems perfectly fine. Simply a list with a link to the Code Sandbox would be sufficient, right? In terms of attribution etc. that can all be gleaned from the individual sandbox example.

I'll submit a pull request where we can discuss further :)

**Comment by davidcetinkaya** [comment]
Well done, I'll check the PR as soon as possible 🙂!

**Comment by davidcetinkaya** [comment]
Added to README in version [v1.1.1](https://github.com/davidcetinkaya/embla-carousel-react/releases/tag/v1.1.1) 🚀.

**Comment by bilogic** [comment]
Hi all,

I copied the ```useInterval``` changes into my example, but keep getting this ```TypeError: Object(...) is not a function```, any idea how to debug? The stack frames display nothing useful. Google doesn't help either. Thank you.
![image](https://user-images.githubusercontent.com/946010/83325783-b21e8380-a2a1-11ea-9cd7-e251999f1b0f.png)

**Comment by xiel** [comment]
@bilogic Did you add the imports and exports for useInterval correctly? You might have mixed up named and default export/import.

Better show the full code or upload your code to codesandbox if you need more assistance. Cheers.

**Comment by bilogic** [comment]
Yea, I have it linked to a whole bunch of other stuff. Let me try codesandbox in a moment.
I did only 3 things:

1. Saved the entire ```useInterval.js``` next to my embla
2. ```import { useInterval } from "./useInterval.js"``` in my embla header
3.  Added this inside my embla under ```useEffect```, which became highlighted as an error
```
  useInterval(() => {
    if (selectedIndex === scrollSnaps.length - 1) {
      scrollTo(0)
    } else {
      scrollNext()
    }
  }, 2000)```

Once I comment out pt 3, my code runs perfectly.

**Comment by bilogic** [comment]
Ok, I managed, but it is showing a very different error. Nonetheless it is code that I was expecting to work... appreciate any debugging help. Thank you!

https://codesandbox.io/s/embla-carousel-react-autoplay-8xtpz

**Comment by readeral** [comment]
Line 3 in your index needs to be named import (curly braces)
`import {Embla_carousel} from "./EmblaCarousel";`

Line 5 in your EmblaCarousel file needs to do the opposite - useInterval is a default export, so is unnamed, should look like this:
`import useInterval from "./useInterval.js";`

Should make your example codesandbox work. Hope that helps!

**Comment by xiel** [comment]
@bilogic Ok, as expected. You mixed up named & default exports two times in the sandbox.


```js
import Embla_carousel from "./EmblaCarousel";

// it must be:
import { Embla_carousel } from "./EmblaCarousel";
```

because you use an **named export** to export the carousel:
`
export const Embla_carousel = props => { //... }
`

and same with the interval, it must be:

`import useInterval from "./useInterval.js";`

when you export useInterval **as default** here

```js
export default function useInterval(callback, delay) {}
```

named export -> use { name } import
default export -> use name import

**Comment by readeral** [comment]
Haha snap @xiel

**Comment by bilogic** [comment]
@readeral @xiel Wow thanks! I spent the last 5 hours on trying to find the error.............
I'm digressing a bit here, but I suppose there is no point in reading the error printouts correct? This come from experience? I'm rather new to react.

**Comment by readeral** [comment]
The hint is "...is not a function" - because you're trying to import a function with a specific name that doesn't exist (in this case useInterval) what does arrive ('undefined') - when you call it as a function, the error says "hold up, that's not a function, that's just a value". So when you see an issue like this "...is not a function" you need to look back at where that function is defined and see what the problem is.

Modules can be particularly tricky, especially when you're not looking out for named and unnamed exports.

The errors in general will be really helpful - it's just that this one in particular is obscured by the subtle error in how you were using the modules.

**Comment by bilogic** [comment]
Got it. Thank you so much for all the help!

**Comment by xiel** [comment]
@bilogic You're welcome, at least you invested a few hours to try to figure it out, this way you will remember for next time. We have all been there! :D Sure it is both experience from debugging for hours in the past, but also knowledge of JS fundamentals ;)

I can only recommend you to read about JS, not only react. Because when things get messy you need to know what is really happening (react has nothing to do with this error for example).
For example: https://exploringjs.com/impatient-js/ch_modules.html#named-exports-and-imports

**Comment by davidcetinkaya** [comment]
Thanks a bunch for the awesome help @xiel and @readeral, I appreciate it 🎉 .
