### ISSUE TITLE
package.json includes React in dependencies AND peerDependencies

### ISSUE THREAD

**Issue by chrisrichard** [davidcetinkaya/embla-carousel-react#24]
embla-react-carousel ends up with its own copy of react in its node_modules and this in turn adds unnecessary bloat to web bundles. My understanding is that typically React-based libraries like this should only list 'react' and 'react-dom' as dev and peer dependencies.

**Comment by chrisrichard** [comment]
https://github.com/davidcetinkaya/embla-carousel-react/pull/25

**Comment by davidcetinkaya** [comment]
Hello @chrisrichard,
Thanks a lot for noticing this and taking time to create a pull request #25 💪. I will take a look at this as soon as possible and get back to you when I've done so.

Cheers!
David

**Comment by garethweaver** [comment]
Not only does it add bloat but it also stops hooks working when imported into as a component into another app.

```
Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.
```

**Comment by davidcetinkaya** [comment]
Thanks for the additional input @garethweaver. Release [v1.3.2](https://github.com/davidcetinkaya/embla-carousel-react/releases/tag/v1.3.2) fixes this issue. I'd very much appreciate if you could confirm if this is working as expected @chrisrichard. 

Best,
David

**Comment by garethweaver** [comment]
No worries!
