### ISSUE TITLE
Prevent click event on child element when dragging

### ISSUE THREAD

**Issue by davidcetinkaya** [davidcetinkaya/embla-carousel-react#26]
I've created this separate issue related to [Embla Carousel React](https://github.com/davidcetinkaya/embla-carousel-react) instead of discussing react specific implementation in the vanilla JS package conversation found [in issue 24](https://github.com/davidcetinkaya/embla-carousel/issues/24).

The **original question** is [here](https://github.com/davidcetinkaya/embla-carousel/issues/24#issuecomment-626216584).

**Comment by davidcetinkaya** [comment]
Thanks for the additional information @coopemor 👍.

For details about how `embla.clickAllowed()` works internally, please expand the collapsable and read the [documentation here](https://github.com/davidcetinkaya/embla-carousel#clickallowed).

So here's **one way to do it in React**:

```jsx
import React, { useCallback } from "react";
import { useEmblaCarousel } from "embla-carousel-react";

const EmblaCarouselComponent = ({ children }) => {
  const [EmblaCarouselReact, embla] = useEmblaCarousel({ loop: false });

  const onSlideClick = useCallback(
    slideIndex => () => {
      if (embla && embla.clickAllowed()) {
        // Do your magic
        console.log(`You clicked on slide with index ${slideIndex}`);
      }
    },
    [embla]
  );

  return (
    <div className="embla">
      <EmblaCarouselReact className="embla__viewport">
        <div className="embla__container">
          {children.map((Child, index) => (
            <div
              key={index}
              onClick={onSlideClick(index)}
              className="embla__slide"
            >
              {Child}
            </div>
          ))}
        </div>
      </EmblaCarouselReact>
    </div>
  );
};

export default EmblaCarouselComponent;
```

Let me know if this helps you on the right track 🙂!

Best,
David

**Comment by coopemor** [comment]
Perfect @davidcetinkaya! This got me up and running. I finally have a product photo carousel with zoom I feel good about.

FWIW I found your package inspecting the source of https://stojo.co/.

**Comment by davidcetinkaya** [comment]
I'm happy it helps @coopemor 🙂.

Thanks a lot for sharing the link to the website where you found the Embla package, it's great to see how Embla is used on production sites!
