### ISSUE TITLE
Getting errors every time I make a change in the code

### ISSUE THREAD

**Issue by daiky00** [davidcetinkaya/embla-carousel-react#27]
### Issue
So, I am using Gatsby in combination with embla-carousel-react and every time I make a change in the code and save and the hot reloader runs I get all these errors.

![Screen Shot 2020-05-11 at 8 15 41 PM](https://user-images.githubusercontent.com/15005162/81627704-62e0e380-93c4-11ea-90ca-a8ef83ba0764.png)
![Screen Shot 2020-05-11 at 8 15 58 PM](https://user-images.githubusercontent.com/15005162/81627708-65433d80-93c4-11ea-8dff-2b44edab724d.png)

### This is all my code

```jsx
import React, { Fragment, useEffect, useCallback, useState } from 'react'
import { useEmblaCarousel } from 'embla-carousel-react'
import { Img } from '~/utils/styles'
import { Dot, Dots } from './styles'
import { RightOutlined, LeftOutlined} from '@ant-design/icons';
import styles from './index.module.less';


const Carousel = ({ images }) => {
  const multiple = images && images.length > 1;
  const [EmblaCarouselReact, embla] = useEmblaCarousel({loop: true, draggable: multiple, align: 'center'})
  const [scrollSnaps, setScrollSnaps] = useState([]);
  const [slide, setSlide] = useState(0);
  const scrollTo = useCallback(index => embla.scrollTo(index), [embla]);
  const scrollPrev = useCallback(() => embla.scrollPrev(), [embla]);
  const scrollNext = useCallback(() => embla.scrollNext(), [embla]);

  useEffect(() => {
    if (embla) {
      const onSelect = () => setSlide(embla.selectedScrollSnap());
      setScrollSnaps(embla.scrollSnapList());
      embla.on("select", onSelect);
      onSelect();
    }
  }, [embla]);

  return (
    <div className={styles.carouselWrapper}>
      <div className={styles.carouselHolder}>
        <EmblaCarouselReact>
          <div className={styles.carouselImageWrapper}>
            {images.map(image => (
              <Img
                key={image.id}
                className={styles.carouselImage}
                imgStyle={{objectFit: 'scale-down', maxWidth:  600, maxHeight: 600}}
                fluid={image.localFile.childImageSharp.fluid}
              />
            ))}
          </div>
        </EmblaCarouselReact>
      </div>
      {images && images.length > 1 &&
        <Fragment>
          <LeftOutlined
            className={styles.leftArrow}
            onClick={() => scrollPrev()}
          />
          <RightOutlined
            className={styles.rightArrow}
            onClick={() => scrollNext()}
          />
          <Dots>
            {scrollSnaps.map((snap, index) => (
              <Dot
                key={index}
                index={index}
                slide={slide}
                onClick={() => scrollTo(index)} />
            ))}
          </Dots>
        </Fragment>
      }
    </div>
  )
}

export default Carousel;
```

**Comment by davidcetinkaya** [comment]
Hello Francisco (@daiky00),

Thanks for reporting this issue, I also noticed it two days ago when messing around with one of the CodeSandboxes. The error messages indicate that this isn't a bug in your code, but rather some issue with the vanilla JS package [Embla Carousel](https://github.com/davidcetinkaya/embla-carousel/) or [Embla Carousel React](https://github.com/davidcetinkaya/embla-carousel-react/).

The React package calls `embla.destroy()` every time the component unmounts (in this case when webpack reloads stuff) and is trying to access embla methods no longer available. I'll have to dig further and will get back to you as soon as I have something.

Best,
David

**Comment by davidcetinkaya** [comment]
Hi again Francisco (@daiky00),

I've just released patch [v1.3.3](https://github.com/davidcetinkaya/embla-carousel-react/releases/tag/v1.3.3) that comes with a fix for this issue. Please bump your [embla-carousel-react](https://github.com/davidcetinkaya/embla-carousel-react/) package to the latest in order to test it.

I'd very much appreciate if you could confirm this solves the issue.

Thanks in advance!
David

**Comment by davidcetinkaya** [comment]
Hello Francisco (@daiky00),

Have you had a chance to test if the patch release solves this issue?

Kindly 
David

**Comment by davidcetinkaya** [comment]
Closing this due to lack of response. Feel free to re-open this issue if you’re still experiencing problems when building your code.
