### ISSUE TITLE
Embla Carousel with Gatsby

### ISSUE THREAD

**Issue by tiagofsanchez** [davidcetinkaya/embla-carousel-react#28]
Hi David, 
First of all thank you and Tobias for this. Really nice work! 

Wanted to understand if when using Embla with Gatsby you are having any issues with text-alignment? I am not sure why, on my [project](https://crushingwfh.com/), after using embla, everything is aligned center. 

In case you need to check, my project [repo](https://github.com/tiagofsanchez/wfh-tools). 

Any pointers would be appreciated. 
Cheers, 
Tiago

**Comment by davidcetinkaya** [comment]
Hello Tiago (@tiagofsanchez),
Thank you for the appreciation 👍🏻.

That sounds a bit strange 😅. Do you mean that every piece of text on your website is aligned center or only the text inside the Embla Carousel component?

Kindly,
David

**Comment by tiagofsanchez** [comment]
Hi @davidcetinkaya, 

Yes, every single piece of text is now aligned center. Very strange... I don't thing that happened to @gunnarx2 Gatsby project...But not sure why this is happening. 

Will try to do a couple of debugs on my end and let you know. If you have any pointers for me that would be great :) 

Cheers

**Comment by tiagofsanchez** [comment]
It is very strange @davidcetinkaya , 

I have tried to replicate the error but can't... [Here](https://codesandbox.io/s/carouselwithgatsby-8qhsp?file=/src/components/emblaCarousel.js). It works well, however in my [project](https://crushingwfh.com/) it does that thing... aligning everything to the center. However, if you go into the blog [(articles)](https://crushingwfh.com/articles) page and refresh there it works fine. In fact, it loads well for any slug, but the main one where the Embla Carousel is... 

This however, only behaves like that in production and not in development. 

Still haven't found the issue... any pointers would be appreciated.

**Comment by davidcetinkaya** [comment]
Hello again @tiagofsanchez,

Something strange is going on indeed. If you look at the screenshot, you have 2 `<body>` tags:

<img width="442" alt="text-align-issue" src="https://user-images.githubusercontent.com/11529148/82291934-2c016380-99aa-11ea-9ee6-907612bc2b27.png">

...this isn't by purpose right? And the `MuiTypography-alignCenter` gets applied on many places including the `<body>` tag. I'm guessing this isn't intended either?

Have you closed all HTML/JSX tags properly?

Kindly,
David

**Comment by tiagofsanchez** [comment]
Hi @davidcetinkaya, 

Yes, Embla is not causing the issue. I can confirm that as I could now solve it. 
First things first... [Embla works great with Gatsby](https://8qhsp.sse.codesandbox.io/) and thank you very much for that :)

As I tried to make sense out of the issue, and thank you for pointing me to the right direction, I found this [issue](https://github.com/gatsbyjs/gatsby/issues/17676) in Gatsby. There was a difference between styles in development mode and production that I was able to fix by using the [gatsby-plugin-material-ui](https://www.gatsbyjs.org/packages/gatsby-plugin-material-ui/). I was not using it and that might have been the issue. 

Anyway, thank you for your help and for Embla with hooks 👍 

Cheers, 
Tiago

**Comment by davidcetinkaya** [comment]
Hello @tiagofsanchez,

I'm happy to hear that you solved the issue. And thank you for taking time to share your appreciation, it's motivating 🙏. All cred goes to Tobias (@gunnarx2) for bringing the `useEmblaCarousel` hook to Embla Carousel React ⭐.

Please feel free to submit a new issue if you have other questions or experiencing any issues with Embla. Until then, enjoy 🙂!
