### ISSUE TITLE
Example with styled-components

### ISSUE THREAD

**Issue by bilogic** [davidcetinkaya/embla-carousel-react#29]
Hi,

Possible to include an example of how to use this with https://github.com/styled-components/styled-components? Thank you.

**Comment by davidcetinkaya** [comment]
Hello @bilogic,

Thank you for your question. I will create an example of how to use Embla with the styled components lib as soon as possible.

In the meantime, I’m going to add the label `help wanted` to see if any Embla React user out there is up for the task before I get a chance to do so.

Cheers!
David

**Comment by gunnarx2** [comment]
Hi @bilogic!

I've created [this example](https://codesandbox.io/s/embla-carousel-react-styled-components-we2je) for you. Does it help you?

**Comment by bilogic** [comment]
@gunnarx2 yes it does. Thank you!

**Comment by bilogic** [comment]
Pardon me, I'm getting a little confused here regarding ```components/EmblaCarousel.js``` and ```components/EmblaCarouselButtons.js``` found in the example.

1. What does ```embla-carousel-react``` offer on top of ```embla-carousel```? I was expecting a ready to use component that just needed styling with ```styled-components```

2. Must I recreate ```components/EmblaCarousel.js``` and ```components/EmblaCarouselButtons.js``` in my code?

Thank you.

**Comment by bilogic** [comment]
Ok, I figured out that I must recreate ```EmblaCarousel.js``` and ```EmblaCarouselButtons.js```, I still face the following issues (Sorry, the amount of CSS in the example was a bit overwhelming for me):

1. How do I move the dots inside the ```Viewport```? (Overlay onto the slides like the prev/next arrows)?
2. How do I define/remove the carousel/slide's aspect ratio constraint? I'm looking to make a ```100vh``` and ```100vw``` carousel. I was able to handle the slide pan/scan using ```backgroundSize: "cover",``` and ```backgroundPosition: "center",``` with other carousels
3. How to not show part of the previous and next slides that's currently behind the ```prev``` and ```next``` buttons?

Thank you!

**Comment by davidcetinkaya** [comment]
Hello @bilogic,

The [`embla-carousel`](https://github.com/davidcetinkaya/embla-carousel) package is a Vanilla JavaScript carousel for the web. And [`embla-carousel-react`](https://github.com/davidcetinkaya/embla-carousel-react) is a tiny React wrapper on top of the vanilla JavaScript package that enables the use of Embla Carousel for React devs.

The answer to your second question is yes, you’ll have to recreate these files. If you read the description on the vanilla JavaScript repo for Embla Carousel it says:

> Extensible bare bone carousels for the web. Build awesome carousels by extending them with your own CSS and JavaScript. Embla Carousel is dependency free and 100% open source.

So the main difference between Embla and other carousel libs is that it doesn’t come with a huge set of features out of the box. Embla is a slim library that has a rich API for users to use and extend it to their liking.

Kindly,
David

**Comment by bilogic** [comment]
Yes @davidcetinkaya, thanks! I'm starting to get the hang of it.

> 2. How do I define/remove the carousel/slide's aspect ratio constraint? I'm looking to make a `100vh` and `100vw` carousel. I was able to handle the slide pan/scan using `backgroundSize: "cover",` and `backgroundPosition: "center",` with other carousels
Solved at CSS of ```SlideInner```'s ```padding-bottom: 46%;``` and removed ```Content```'s ```padding```, ```margin```

> 3. How to not show part of the previous and next slides that's currently behind the `prev` and `next` buttons?
removed ```Content```'s ```max-width```

Still trying to overlap the dots. :)

**Comment by bilogic** [comment]
> 1. How do I move the dots inside the `Viewport`? (Overlay onto the slides like the prev/next arrows)?

Decrease ```Dots```'s ```top: 100%```

**Comment by bilogic** [comment]
@davidcetinkaya @gunnarx2 thanks for all your help!
I managed to figure out everything required.
Embla is the most flexible of all 8 carousels that I tried so far. Keep up the great work!

**Comment by davidcetinkaya** [comment]
Hello again @bilogic,

Nice going solving it all 🙂!
Let us know if you have questions regarding the lib in the future. Until then, enjoy!

Cheers!
David
