### ISSUE TITLE
would love to have a costum dot navigation

### ISSUE THREAD

**Issue by iryanrachman** [davidcetinkaya/embla-carousel-react#32]
just asking, i am trying to add a title to each dot navigation, but with a different value is it possible ? if so how ?

**Comment by davidcetinkaya** [comment]
Hello @iryanrachman,

Thank you for your question. Of course it’s quite possible. Embla doesn’t come with any predefined dot nav but provides the API needed.

What have you tried so far? Have you had a look at the [Basic Setup](https://codesandbox.io/s/embla-carousel-react-basic-setup-znjzv) example provided in the readme? And tried modifying it?

Kindly
David

**Comment by iryanrachman** [comment]
i tried this tho, 

first i have a sass, so i import it like usual 

```  let button = "button-carousel" ```


then i tried to make different class using index.. idk where do i get it wrong.. because it is not styled properly, this is actually a hack and not effeicent because i tried to add it one by one using &:after then content : "bla bla"... it works when i dont use button + index...

the thing that i find is binding or  maybe connecting two array or maybe adding the some kind of content in each array..

for a demonstration that i want to achive is in iea.org below the video... they use somekind of timeline


``` const renderDots = useCallback(() => {
	if (embla) {
    
    console.log(embla.scrollSnapList)
    return embla.scrollSnapList().map((snap, index) => (
      

      // <ProgramTitle/>

			<button
				key={index}
				active={index === slide}
				aria-label={`Scroll to slide number ${index + 1}`}
				// aria-label={`Scroll to slide number ${index + 1}`}
				type="button"
        onClick={() => embla.scrollTo(index)}
        className={`${button + index}`}
			>
        {/* <button className={hr}/> */}
      </button>
		));
	} ```

**Comment by iryanrachman** [comment]
i have found that the purge css is the one who removed the content.. so t works but i is not pretty good solution because i input it manually..
