### ISSUE TITLE
Make emblaRef optional

### ISSUE THREAD

**Issue by gunnarx2** [davidcetinkaya/embla-carousel-react#6]
Hi @davidcetinkaya!

I'd like to discuss the `emblaRef` prop.

I noticed that `emblaRef` is required, but should it really be that? I understand that for most part you want to access the ref so you can execute stuff through the api, but not always.

Let's say (for some reason) you want to initiate Embla just as it is, nothing more than default, then you have to define a ref that you'll never use.

I know this is edge case, but it feels more correct to make it optional.

Peace ☮️

**Comment by davidcetinkaya** [comment]
This is now a feature of version [1.2.0](https://github.com/davidcetinkaya/embla-carousel-react/releases/tag/v1.2.0) 🚀.
