### ISSUE TITLE
Create counter widget

### ISSUE THREAD

**Issue by lucasdon** [davidcetinkaya/embla-carousel-react#8]
Thank you for this project. The physics are great. I managed to set up a very nice portfolio-slider with it and everything works fine. But now I'm trying to set up a counter-widget (eg 2of22) I'm quite new to React-land and struggle to connect all loose endings.

I'm using Embla via React Hooks. And I manage to get the current Index as followed: 

```javascript
const [embla, setEmbla] = useState(null)

useEffect(() => {
  if (embla) {
    embla.on('select', () => {
      console.log(`Current index is ${embla.selectedScrollSnap()}`) 
    })
  }
}, [embla])
```

And I can get the count of my Array/Total Numer of Slides:

```javascript
const slidesCountAll = data.nodeProjekt.filter(({ relationships }) => relationships.childImageSharp.fluid)
const numSlides = slidesCountAll.length

useEffect(() => {
  console.log(`Number of slides ${numSlides}`) 
})
```

But I 'm not able to return them as I need to. Like 

```jsx
<span>{indexSelected}{numSlides}</span>
```

Sorry to bother you with this noobs question

**Comment by lucasdon** [comment]
Dear David,

thank you for your reply and for reformating my code. I will try harder to get it working right the next time.

I'm trying to reproduce this slide number/slides-widget like for flickity. [Here is a Pen](https://codepen.io/desandro/pen/dpPzab) and a screenshot: 

<img width="497" alt="Bildschirmfoto 2019-10-13 um 12 19 20" src="https://user-images.githubusercontent.com/15727423/66714175-d893bb00-edb3-11e9-9922-db29271b9838.png">

In the meantime, I figured out that my solution from above would only work after the next slide is selected (I  missed that `selectedIndex` is 0-based) So the first selected slide was "1" and look right to me at first... But it has to be 1 when the component loads, not when it updates...

Have a good day!

**Comment by davidcetinkaya** [comment]
Hello @lucasdon,

Thanks for geting back to me. Great, the attached screenshot helps me understand 🙂.

I will suggest a solution as soon as I get the chance.

Thanks for your patience!

**Comment by davidcetinkaya** [comment]
Hi @lucasdon,

I've setup a [CodeSandbox](https://codesandbox.io/s/embla-carousel-react-github-issue-8-3lqf0) to demonstrate how a **counter widget** can be achieved with Embla Carousel.

Have a look and let me know if you have any questions.

Best,
David

**Comment by lucasdon** [comment]
Hi David,
thank you very much! Just can say:
![wow](https://user-images.githubusercontent.com/15727423/66749778-fda72d00-ee8a-11e9-88a5-ee30d82b6dee.gif)


Ah. I can see now what I missed. 
Thank you for clarifying it this quick and all your efforts!!!

Best, 
Oliver

**Comment by davidcetinkaya** [comment]
Hello @lucasdon,

**Comment by davidcetinkaya** [comment]
Hello @lucasdon, 

I'm glad I could help 🙂. If you want to support this project, please consider recommending it to a friend and/or giving it a star. Don't feel obligated to, but it really helps.

Cheers!
David
