### ISSUE TITLE
Pagination: Possibility to update the content of the embla object

### ISSUE THREAD

**Issue by FarouHub** [davidcetinkaya/embla-carousel-react#9]
Hi,
I have a lot of datas and i want to upload the images with a pagination system.
The problem is when i push the datas into the slides array, the embla object is no refreshed.
embla.[API docs](https://github.com/davidcetinkaya/embla-carousel/blob/master/README.md#changeoptionsoptions) scrollSnapLis[API docs](https://github.com/davidcetinkaya/embla-carousel/blob/master/README.md#changeoptionsoptions) t() stay with the old number of slides and embla.canScrollNext() return false while there are new slides.

```jsx 
<EmblaCarousel>    
    {slides.map((slide, index) => (<EmblaCard key={index} slide={slide} />))}
</EmblaCarousel>
```

Thanks for your help

**Comment by davidcetinkaya** [comment]
Hello Nicolas (@FarouHub),

Thank you for your question. When your data is ready you can use the following API method:

```javascript 
embla.changeOptions({})
```

As described in the [API docs](https://github.com/davidcetinkaya/embla-carousel/blob/master/README.md#changeoptionsoptions):

> Applies passed options by doing all the necessary calculations and initialising the carousel from scratch.

If you pass an empty object the carousel will just re-initialize with the same options as before.

I hope this helps! Let me know if you have more questions or it didn’t help for some reason. I’d appreciate if you can confirm if this works for you.

Kindly,
David

**Comment by FarouHub** [comment]
Hello David,
thank you for your reactivity. I really appreciate.
Yes it's working !! Thank very much. 

In my case when i arrived at the end of my page (20 elements), the next button is disabled.
Then if i have a next page, i load the next element. `embla.changeOptions({})` while recalculate the embla object but don't enable the next button. So i had a manually `setNextBtnEnabled(true)`..
And that work really fine.

```
useEffect(() => {
    if(preChildLength !== children.length){
      embla.changeOptions({});
      setNextBtnEnabled(true);
      setPreChildLength(children.length);
    }
  }, [children]);
```

**Comment by davidcetinkaya** [comment]
Hi Nicolas (@FarouHub),

I’m glad I could help 🙂. In your case setting  
`setNextBtnEnabled(true)` seems to work but I’d recommend doing it this way instead:

```javascript
useEffect(() => {
  if (preChildLength !== children.length) {
    embla.changeOptions({});
    setNextBtnEnabled(embla.canScrollNext()); // Change this line to this
    setPreChildLength(children.length);
  }
}, [children]);
```

The reason for this is that `embla.changeOptions({})` will update the carousel and just setting `setNextBtnEnabled()` to `true` could cause unintended bugs for different use cases than your current use case.

Thanks you again for your question!

Best,
David
